### ISSUE TITLE
does it support table in pptx?

### ISSUE THREAD

**Issue by ylyxf** [Coreoz/PPT-Templates#2]
dose it suppor table like using  ${iterator} to loop rows in a table ?

**Comment by amanteaux** [comment]
Thank you for your interest in PPT-Templates.

Currently we do not provide such functionality that will enable to loop over a PPT element.
The thing is that in a PPT document, it is easy to write elements outside of the slide frame. And when duplicating elements in a slide, you will encounter this issue very fast.

However though it is not perfect, what you can do is prepare a table with N rows with numbered templated variables. This way you will be guaranteed that the table will not exceed the slide frame.
For example you will write in your template:

| First Name      | Last Name      |
| --------------- | -------------- |
| $/firstname:1/  | $/lastname:1/  |
| $/firstname:2/  | $/lastname:2/  |
| $/firstname:3/  | $/lastname:3/  |

So if you only have 2 rows, you will have in your slide:

| First Name      | Last Name      |
| --------------- | -------------- |
| Christina       | Proper         |
| Bradley         | Bruner         |
| -                | -               |

**Comment by ghost** [comment]
Hello, @amanteaux does iterator concept in ppt added?

**Comment by amanteaux** [comment]
Hello @bhardwaz,

The concept of iterator has not been added and will not likely be added in the future.

We think this library is not the proper tool to do that. This may sound weird for a template library, but generating a PPT presentation from a PPT template is a rather different process than generating HTML from a JSP or a Freemarker file.
Whereas HTML in its text form is easily modifiable by developers, no sane person would ever write manually the XML files that compose the PPT document. To modify a PPT document, you need to use a WYSIWYG editor which was never thought to build complex PPT templates. An example is how to add a meta data to an image that can be used later in an automated tool: actually there is no way to accomplish that :(. This is why in PPT Templates we choose to use the link on the image to set these meta data. That works but it remains a sort of a hack that is far for perfect: you cannot use an image template and in this template put a real link to that image (the link will already be used to store the meta data).

The problem with table iterator is that it is not possible to put a link to an entire table, so to implement this functionality, we will need to identify a text marker inside the table that say "ok this table will contain iterable rows". We will then need to remove this marker row, look up for the next row and then at last duplicate this row and replace its variables.
Moreover:
- duplicating a shape in a PPT document can lead to a result that goes beyond the slide frame,
- implementing this feature for the Table shape would be completely different than implementing this feature for the Group shape.

We think the iterator feature is too much a hack to be implemented here.

So if you really need this feature, what you can do is use directly POI XSLF to handle a table or a shape the way you want, and then process your document with PPT Templates if you have variables left to be handled.
